### ISSUE TITLE
Validation dataset

### ISSUE THREAD

**Issue by Elnur21** [Navidfoumani/Disjoint-CNN#2]
Hello,
Here the codes are like this, but there is a problem, validation dataset is in train dataset

val_index = np.random.randint(0, np.int(x_train.shape[0]), np.int(x_train.shape[0] / 10), dtype=int)
x_val = x_train[val_index, :]
y_val = y_train[val_index, :]

classifier = fit_classifier(all_labels_new, x_train, y_train, x_val, y_val, epochs, batch_size)

**Comment by Navidfoumani** [comment]
Hi,
Thank you for highlighting this. Indeed, the code you mentioned is specifically tailored for datasets with limited training samples, where sacrificing a portion for validation might be impractical. This approach is particularly suitable when the test and train datasets share similar data distributions, as seen in UEA datasets. However, for datasets with over 100 samples per class, it's advisable to split the training set into separate training and validation subsets.

Appreciate your attention to detail.
Cheers,
Navid
